Implement -d option, check $REVEAL_PATH after processing options

diff --git a/reveal-init b/reveal-init
--- a/reveal-init
+++ b/reveal-init
@@ -23,12 +23,15 @@ n_err=0    # Number of errors
 n_slide=0  # Number of empty non-vertical slides to create
 
 function warn() {
-    printf "\033[1;33mWARNING\033[0m $1\n"
+    printf "\033[1;33mWARNING\033[0m $1.\n"
 }
 
 function err() {
-    printf "\033[1;31mERROR\033[0m $1\n"
-    n_err=$(( $n_err + 1 ))
+    printf "\033[1;31mERROR\033[0m $1.\n"; n_err=$(( $n_err + 1 ))
+}
+
+function fatal() {
+    printf "\033[1;31mFATAL\033[0m $1.\n"; exit 1
 }
 
 # ===========================
@@ -95,74 +98,24 @@ EXAMPLES\n\n\
 esac
 
 [ $# -eq 0 ] && \
-    err "Directory name not given.\nInvoke '--help' for more information" \
-    && exit 1
+    fatal "Directory name not given.\nInvoke '--help' for more information"
 
-# === CHECK $REVEAL_PATH ===
-
-if [ -z $REVEAL_PATH ]; then
-    warn "\$REVEAL_PATH is empty"
-    printf "Is it:\n  1: The current directory\n  2: You forgot to set a value for it?\n"
-    read -p "[1|2] " rpe_c
-
-    case $rpe_c in
-        1)
-            echo "Okay, \$REVEAL_PATH is the current directory"
-            REVEAL_PATH="."
-            ;;
-        2)
-            echo "Then go set a value for it with 'export'"
-            echo "Aborting..."
-            exit 2
-            ;;
-        *)
-            err "Invalid option, aborting..."
-            exit 2
-            ;;
-    esac
-fi
-
-# Must include:
-#   - $REVEAL_PATH/css/reveal.css
-#   - $REVEAL_PATH/js/reveal.js
-#
-# Warn if absent:
-#   - $REVEAL_PATH/css/theme          (no theme)
-#   - $REVEAL_PATH/lib/js/head.min.js (no plugin)
-#   - $REVEAL_PATH/plugin             (no plugin)
-
-echo "Checking \$REVEAL_PATH..."
-
-! [ -f $REVEAL_PATH/css/reveal.css ] && err "$REVEAL_PATH/css/reveal.css not found"
-! [ -d $REVEAL_PATH/css/theme ] || [[ -z $(ls $REVEAL_PATH/css/theme) ]] && \
-    warn "No theme?" && theme="-"
-
-! [ -f $REVEAL_PATH/js/reveal.js ] && err "$REVEAL_PATH/js/reveal.js not found"
-
-! [ -f $REVEAL_PATH/lib/js/head.min.js ] && \
-  warn "$REVEAL_PATH/lib/js/head.min.js not found, plugins won't be loaded" && \
-  plugins="-"
-
-! [ -d $REVEAL_PATH/plugin ] && warn "No plugin?" && plugins="none"
-
-[ $n_err -gt 0 ] && \
-    printf "\n\033[1;31mFATAL\033[0m Fix the above problem(s) and try again\n" \
-    && exit 3
-
-echo "Done checking."
-
-# ==========================
+# === PROCESS OPTIONS ===
 
 opt=""
 
 for arg in "$@"
 do
     if [ $# -eq 1 ]; then
-        [ -d $1 ] && err "Directory '$1' exists" && exit 4
+        [ -d $1 ] && err "Directory '$1' exists" && exit 1
         dirname=$1 && break
     fi
 
     case $opt in
+        "-d")
+            REVEAL_PATH=$1
+            opt=""
+            ;;
         "-t" | "-title" | "--title")
             title=$1
             opt=""
@@ -200,12 +153,12 @@ do
             ;;
         *)
             case $1 in
-                "-t" | "-title" | "--title" | "-f" | "-theme" | "--theme" \
+                "-d" | "-t" | "-title" | "--title" | "-f" | "-theme" | "--theme" \
                 | "-plugin" | "--plugin" | "-header" | "--header" | "-n")
                     opt=$1;;
                 "--short-tab") t="  ";;
                 "--long-tab") t="    ";;
-                *) err "Invalid option '$1', aborting..." && exit 5;;
+                *) err "Invalid option '$1', aborting..." && exit 1;;
             esac
             ;;
     esac
@@ -215,12 +168,68 @@ done
 [[ $theme == "" ]] && theme="-"
 [[ $plugins == "" ]] && plugins="-"
 
+# =======================
+
+# === CHECK $REVEAL_PATH ===
+
+if [ -z $REVEAL_PATH ]; then
+    warn "\$REVEAL_PATH is empty"
+    printf "Is it:\n  1: The current directory\n  2: You forgot to set a value for it?\n"
+    read -p "[1|2] " rpe_c
+
+    case $rpe_c in
+        1)
+            echo "Okay, \$REVEAL_PATH is the current directory"
+            REVEAL_PATH="."
+            ;;
+        2)
+            echo "Then go set a value for it with 'export'"
+            echo "Aborting..."
+            exit 1
+            ;;
+        *)
+            fatal "Invalid option, aborting.." exit 1
+            ;;
+    esac
+fi
+
+# Must include:
+#   - $REVEAL_PATH/css/reveal.css
+#   - $REVEAL_PATH/js/reveal.js
+#
+# Warn if absent:
+#   - $REVEAL_PATH/css/theme          (no theme)
+#   - $REVEAL_PATH/lib/js/head.min.js (no plugin)
+#   - $REVEAL_PATH/plugin             (no plugin)
+
+echo "Checking \$REVEAL_PATH..."
+
+! [ -d $REVEAL_PATH ] && fatal "\$REVEAL_PATH ($REVEAL_PATH) not found"
+
+! [ -f $REVEAL_PATH/css/reveal.css ] && err "$REVEAL_PATH/css/reveal.css not found"
+! [ -d $REVEAL_PATH/css/theme ] || [[ -z $(ls $REVEAL_PATH/css/theme) ]] && \
+    warn "No theme found" && theme="-"
+
+! [ -f $REVEAL_PATH/js/reveal.js ] && err "$REVEAL_PATH/js/reveal.js not found"
+
+! [ -f $REVEAL_PATH/lib/js/head.min.js ] && \
+    warn "$REVEAL_PATH/lib/js/head.min.js not found, plugins won't be loaded" && \
+    plugins="-"
+
+! [ -d $REVEAL_PATH/plugin ] && warn "No plugin found" && plugins="-"
+
+[ $n_err -gt 0 ] && fatal "Fix the above problem(s) and try again"
+
+echo "Done checking."
+
+# ==========================
+
 # === START COPYING FILES ===
 
 # Make directories
 
 mkdir -p $dirname/js
-[ $? -ne 0 ] && err "Please validate the directory name (DIRNAME)." && exit 6
+[ $? -ne 0 ] && fatal "Please validate the directory name (DIRNAME)"
 mkdir $dirname/css
 
 # Copy themes
