Update reveal-init

diff --git a/reveal-init b/reveal-init
--- a/reveal-init
+++ b/reveal-init
@@ -164,7 +164,7 @@ do
                     ;;
                 "--short-tab") t="  ";;
                 "--long-tab") t="    ";;
-                *) err "Invalid option '$1', aborting..." && exit 1;;
+                *) fatal "Invalid option '$1', aborting..." && exit 1;;
             esac
             ;;
     esac
